### ISSUE TITLE
[BUG] Falha ao deletar um usuário pela API

### ISSUE THREAD

**Issue by rodrigomolter** [Organizacao-Docunder/App#20]
## Título
Falha ao deletar um usuário pela API

## Prioridade
🚨 Alto

## Descrição
Ao tentar deletar um usuário através do endpoint `/user/1` esta retornando um `Internal Server Error`
Sendo 1 o Id do usuário. Id este de um usuário válido e existente

## Passos para reproduzir
1. Identifique o Id do usuário que deseja deletar
2. Faça uma requisição HTTP com o verbo **DELETE** para `localhost:3000/user/1`
3. Observe o retorno

## Resultado esperado
Usuário deveria ser deletado corretamente

## Ambiente
Postman v11.2.26

## Evidência
```bash
[Nest] 1852  - 28/06/2024, 10:18:46   ERROR [ExceptionsHandler]
Invalid `this.prisma.user.delete()` invocation in
\src\user\user.service.ts:119:34

  116 if (!user || user.id != currentUser.id) {
  117   throw new NotFoundException('User not found');
  118 }
→ 119 await this.prisma.user.delete(
Foreign key constraint failed on the field: `(not available)`
PrismaClientKnownRequestError:
Invalid `this.prisma.user.delete()` invocation in
\src\user\user.service.ts:119:34

  116 if (!user || user.id != currentUser.id) {
  117   throw new NotFoundException('User not found');
  118 }
→ 119 await this.prisma.user.delete(
Foreign key constraint failed on the field: `(not available)`
    at In.handleRequestError (\node_modules\@prisma\client\runtime\library.js:122:6854)
    at In.handleAndLogRequestError (\node_modules\@prisma\client\runtime\library.js:122:6188)
    at In.request (\node_modules\@prisma\client\runtime\library.js:122:5896)
    at l (\node_modules\@prisma\client\runtime\library.js:127:10871)
    at UserService.deleteUser (\src\user\user.service.ts:119:5)
    at UserController.delete (\src\user\user.controller.ts:72:5)
    at \node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at \node_modules\@nestjs\core\router\router-proxy.js:9:17
```

**Comment by rodrigomolter** [comment]
Endpoint deletando corretamente.

Resultado obtido como o esperado.
