### ISSUE TITLE
[BUG] [API] Falha ao cadastrar pergunta secreta com QuestionId repetido pela API

### ISSUE THREAD

**Issue by rodrigomolter** [Organizacao-Docunder/App#21]
## Título
Falha ao cadastrar pergunta secreta com QuestionId repetido pela API

## Prioridade
⚡Medio

## Task
#15 

## Descrição
Ao realizar o cadastro de um novo usuário pela API, passando na `secretAnswers` dois `questionIds' iguais, esta retornando um `Internal Server Error`

## Passos para reproduzir
1. Faça uma requisição HTTP com o verbo **POST** para `localhost:3000/user` com o body contendo dois questionIds com o mesmo valor:
```json
{
    "name": "Rogerio",
    "email": "rogerio12@email.com", 
    "password": "T3ste@123",
    "secretAnswers": 
    [
        {
        "questionId": 1,
        "answer": "Johanna"
        },
        {
        "questionId": 1,
        "answer": "Thor"
        },
        {
        "questionId": 3,
        "answer": "Escola Golias"
        }
    ]
}
```
2. Observe o erro

## Resultado esperado
Não deveria ser possível fazer o cadastro e retornar uma mensagem de erro informando que os questionIds devem ser únicos.

## Ambiente
Postman v11.2.26

## Evidência
```bash
Invalid `this.prisma.user.create()` invocation in
\src\user\user.service.ts:29:48

  26 const hashedPassword = await hashText(createUserDto.password);
  27 const hashedAnswer = await hashSecretQuestions(secretQuestions);
  28
→ 29 const createdUser = await this.prisma.user.create(
Unique constraint failed on the fields: (`userId`,`questionId`)
PrismaClientKnownRequestError:
Invalid `this.prisma.user.create()` invocation in
\src\user\user.service.ts:29:48

  26 const hashedPassword = await hashText(createUserDto.password);
  27 const hashedAnswer = await hashSecretQuestions(secretQuestions);
  28
→ 29 const createdUser = await this.prisma.user.create(
Unique constraint failed on the fields: (`userId`,`questionId`)
    at In.handleRequestError (\node_modules\@prisma\client\runtime\library.js:122:6854)
    at In.handleAndLogRequestError (\node_modules\@prisma\client\runtime\library.js:122:6188)
    at In.request (\node_modules\@prisma\client\runtime\library.js:122:5896)
    at l (\node_modules\@prisma\client\runtime\library.js:127:10871)
    at UserService.createUser (\src\user\user.service.ts:29:25)
    at UserController.create (\src\user\user.controller.ts:47:12)
    at \node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at \node_modules\@nestjs\core\router\router-proxy.js:9:17
```

**Comment by rodrigomolter** [comment]
Solucionado no 066e874
